-- MySQL Script generated by MySQL Workbench
-- 05/30/19 10:54:34
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema scuola
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema scuola
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `scuola` ;
USE `scuola` ;

-- -----------------------------------------------------
-- Table `comune`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comune` (
  `codice` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `regione` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codice`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `classe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `classe` (
  `anno` TINYINT NOT NULL,
  `sezione` CHAR(1) NOT NULL,
  PRIMARY KEY (`anno`, `sezione`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `studente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `studente` (
  `codice_fiscale` CHAR(16) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `cognome` VARCHAR(45) NOT NULL,
  `comune_residenza` INT NOT NULL,
  `classe_anno` TINYINT NOT NULL,
  `classe_sezione` CHAR(1) NOT NULL,
  `nazione` VARCHAR(45) NULL,
  PRIMARY KEY (`codice_fiscale`),
  INDEX `ResidenzaStudente_idx` (`comune_residenza` ASC),
  INDEX `ClasseFK_idx` (`classe_anno` ASC, `classe_sezione` ASC),
  CONSTRAINT `ResidenzaStudente`
    FOREIGN KEY (`comune_residenza`)
    REFERENCES `comune` (`codice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ClasseFK`
    FOREIGN KEY (`classe_anno` , `classe_sezione`)
    REFERENCES `classe` (`anno` , `sezione`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `insegnante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `insegnante` (
  `codice_fiscale` CHAR(16) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `cognome` VARCHAR(45) NOT NULL,
  `comune_residenza` INT NOT NULL,
  `comune_nascita` INT NOT NULL,
  PRIMARY KEY (`codice_fiscale`),
  INDEX `ResidenzaInsegnante_idx` (`comune_residenza` ASC),
  INDEX `NascitaInsegnante_idx` (`comune_nascita` ASC),
  CONSTRAINT `NascitaInsegnante`
    FOREIGN KEY (`comune_nascita`)
    REFERENCES `comune` (`codice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ResidenzaInsegnante`
    FOREIGN KEY (`comune_residenza`)
    REFERENCES `comune` (`codice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `scuola`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scuola` (
  `codice` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `comune` INT NOT NULL,
  PRIMARY KEY (`codice`),
  INDEX `ScuolaRisiede_idx` (`comune` ASC),
  CONSTRAINT `ScuolaRisiede`
    FOREIGN KEY (`comune`)
    REFERENCES `comune` (`codice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `materia` (
  `codice` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codice`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `argomento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `argomento` (
  `codice` INT NOT NULL AUTO_INCREMENT,
  `codice_materia` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `ore` TINYINT NOT NULL,
  PRIMARY KEY (`codice`, `codice_materia`),
  INDEX `MateriaArgomento_idx` (`codice_materia` ASC),
  CONSTRAINT `MateriaArgomento`
    FOREIGN KEY (`codice_materia`)
    REFERENCES `materia` (`codice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `valutazione`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `valutazione` (
  `codice_argomento` INT NOT NULL,
  `codice_materia` INT NOT NULL,
  `studente` CHAR(16) NOT NULL,
  `voto` DECIMAL NOT NULL,
  INDEX `ArgomentoStudente1_idx1` (`codice_argomento` ASC, `codice_materia` ASC),
  INDEX `ArgomentoStudente3_idx` (`studente` ASC),
  PRIMARY KEY (`codice_argomento`, `codice_materia`, `studente`),
  CONSTRAINT `ArgomentoStudente1`
    FOREIGN KEY (`codice_argomento` , `codice_materia`)
    REFERENCES `argomento` (`codice` , `codice_materia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ArgomentoStudente3`
    FOREIGN KEY (`studente`)
    REFERENCES `studente` (`codice_fiscale`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parentela`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parentela` (
  `studente_1` CHAR(16) NOT NULL,
  `studente_2` CHAR(16) NOT NULL,
  `grado` VARCHAR(45) NOT NULL,
  INDEX `StudenteParente1_idx` (`studente_1` ASC),
  INDEX `StudenteParente2_idx` (`studente_2` ASC),
  PRIMARY KEY (`studente_1`, `studente_2`),
  CONSTRAINT `StudenteParente1`
    FOREIGN KEY (`studente_1`)
    REFERENCES `studente` (`codice_fiscale`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `StudenteParente2`
    FOREIGN KEY (`studente_2`)
    REFERENCES `studente` (`codice_fiscale`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `insegnamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `insegnamento` (
  `insegnante` CHAR(16) NOT NULL,
  `codice_materia` INT NOT NULL,
  `classe_anno` TINYINT NOT NULL,
  `classe_sezione` CHAR(1) NOT NULL,
  `ore_settimanali` TINYINT NOT NULL,
  INDEX `DocenteMateriaClasse1_idx` (`insegnante` ASC),
  INDEX `DocenteMateriaClasse2_idx` (`codice_materia` ASC),
  INDEX `ClasseAnnoFK_1_idx` (`classe_anno` ASC, `classe_sezione` ASC),
  PRIMARY KEY (`insegnante`, `codice_materia`, `classe_anno`, `classe_sezione`),
  CONSTRAINT `DocenteMateriaClasse1`
    FOREIGN KEY (`insegnante`)
    REFERENCES `insegnante` (`codice_fiscale`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `DocenteMateriaClasse2`
    FOREIGN KEY (`codice_materia`)
    REFERENCES `materia` (`codice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ClasseAnnoFK_1`
    FOREIGN KEY (`classe_anno` , `classe_sezione`)
    REFERENCES `classe` (`anno` , `sezione`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `insegnamento_altra_scuola`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `insegnamento_altra_scuola` (
  `insegnante` CHAR(16) NOT NULL,
  `codice_scuola` INT NOT NULL,
  INDEX `InsegnanteAltraScuola_idx` (`insegnante` ASC),
  INDEX `AltraScuola_idx` (`codice_scuola` ASC),
  PRIMARY KEY (`insegnante`, `codice_scuola`),
  CONSTRAINT `InsegnanteAltraScuola`
    FOREIGN KEY (`insegnante`)
    REFERENCES `insegnante` (`codice_fiscale`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `AltraScuola`
    FOREIGN KEY (`codice_scuola`)
    REFERENCES `scuola` (`codice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `propedeuticita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `propedeuticita` (
  `materia` INT NOT NULL,
  `argomento_prima` INT NOT NULL,
  `argomento_dopo` INT NOT NULL,
  INDEX `Argomento_prima_idx` (`materia` ASC, `argomento_dopo` ASC),
  INDEX `Argomento_dopo_idx` (`materia` ASC, `argomento_prima` ASC),
  PRIMARY KEY (`materia`, `argomento_prima`, `argomento_dopo`),
  CONSTRAINT `Argomento_prima`
    FOREIGN KEY (`argomento_prima` , `materia`)
    REFERENCES `argomento` (`codice` , `codice_materia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Argomento_dopo`
    FOREIGN KEY (`argomento_dopo` , `materia`)
    REFERENCES `argomento` (`codice` , `codice_materia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
